/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.4/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
    java
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

repositories {
    mavenCentral()
}

dependencies {
    // If you're using version catalogs (libs.*), keep them:
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    implementation(libs.guava)

    // Otherwise, use normal deps like:
    // testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
    // testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.10.2")
    // implementation("com.google.guava:guava:33.2.1-jre")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

application {
    // IMPORTANT: if your class has `package yilonmah;` use "yilonmah.Yilonmah"
    // If it has NO package line, use just "Yilonmah"
    mainClass.set("yilonmah.Yilonmah")
}

tasks.test {
    useJUnitPlatform()
}

tasks.shadowJar {
    archiveFileName.set("yilonmah.jar")

    // helpful to force the entrypoint in the manifest:
    manifest {
        attributes["Main-Class"] = application.mainClass.get()
    }
}
